name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download dependencies (json, junit, hamcrest)
      run: |
        wget https://repo1.maven.org/maven2/org/json/json/20231013/json-20231013.jar
        wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
        wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

    - name: Compile Java source and test files
      run: |
        mkdir -p build/classes
        javac -cp ".:json-20231013.jar:junit-4.13.2.jar:hamcrest-core-1.3.jar" \
          -d build/classes \
          $(find src -name "*.java") $(find test -name "*.java")

    - name: Run JUnit Tests
      run: |
        java -cp "build/classes:.:json-20231013.jar:junit-4.13.2.jar:hamcrest-core-1.3.jar" \
          org.junit.runner.JUnitCore ProgProperties.TeanantManager ProgSeries.Series
